GET http://localhost:3000

###
GET http://localhost:3000/produtos

###
GET http://localhost:3000/produtos/1

###
POST http://localhost:3000/produtos
Content-Type: application/json

{
  "name": "Category name",
  "description": "Category description"
}

###
PATCH http://localhost:3000/produtos/1
Content-Type: application/json

{
  "name": "Update category name",
  "description": "Update category description"
}

###
DELETE http://localhost:3000/produtos/1