GET http://localhost:3000

###
GET http://localhost:3000/produtos

###
GET http://localhost:3000/produtos/1

###
POST http://localhost:3000/produtos
Content-Type: application/json

{
  "id": 4,
  "code": "P004",
  "name": "Product 4",
  "price": 19.99
}

###
PUT http://localhost:3000/produtos/4
Content-Type: application/json

{
  "code": "P004",
  "name": "Product 4 updated",
  "price": 19.99
}

###
DELETE http://localhost:3000/produtos/3