GET http://localhost:3000

###
GET http://localhost:3000/products

###
GET http://localhost:3000/products/1

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "code": "P008",
  "name": "Incredible Product",
  "price": 39.99
}

###
PUT http://localhost:3000/products/
Content-Type: application/json

{
  "id": 2,
  "code": "P001",
  "name": "Super Awesome Product Updated",
  "price": "29.99"
}

# ###
# PATCH http://localhost:3000/produtos/2
# Content-Type: application/json

# {
#   "name": "Super Awesome Product Updated"
# }

###
DELETE http://localhost:3000/products/1